### ISSUE TITLE
biodocker

### ISSUE THREAD

**Issue by sauloal** [Steven-N-Hart/bior_annotate#2]
May I have the permission to convert and deposit your dockerfile (with small modifications) on the biodocker repository?

regards

**Comment by Steven-N-Hart** [comment]
Absolutely!  😄

**Comment by sauloal** [comment]
Hello Mr. @Steven-N-Hart,

I've manage to convert bior annotate. 
https://github.com/BioDocker/sandbox/tree/master/bior_annotate/2.1.1

I had to convert it to debian but besides that it remains the same.

Could you please check it?
