### ISSUE TITLE
Feature request - ARGV for Compression

### ISSUE THREAD

**Issue by raymond301** [Steven-N-Hart/bior_annotate#4]
Can you add a parameter to the command line arguments to avoid compression?
I nearly always need to uncompress the resulting annotation vcf immediately upon completion, it would be a nice feature to include the decision to compress/uncompress.

-z is the typical single letter reference for compression, and you are not currently using it in your commandline arguments.

**Comment by mikekalmbach** [comment]
This has been added. Use "-z no" to disable compression.
